spring:
  redis:
    host: 10.20.2.12
    port: 7150
  datasource:
    username: wgicheru
    url: jdbc:mysql://10.20.2.51:3306/mobile-banking
    password: 1QAZ2wsx3edc.
  jpa:
    database: mysql
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

  #Flyway
  flyway:
    baselineOnMigrate: true
    enabled: false
    schemas: public

  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          brokers: 10.20.2.148:9092
      bindings:
        handleBCAccountCreation-in-0:
          destination: create-blockchain-account-topic
          group: create-blockchain-account-group
        handleBCAccountEnroll-in-0:
          destination: enroll-blockchain-account-topic
          group: enroll-blockchain-account-group

    function:
      definition: handleBCAccountCreation;handleBCAccountEnroll;

services:
  crypto: http://10.20.2.148:7130/
  core: http://10.20.2.12:8096/
  on-boarding: http://10.20.2.148:8096/
  auth: http://10.20.2.148:8888/
  block-chain: https://10.20.2.120:8091/
  channel-manager: http://10.20.2.201:7600/


auth:
  wallet: Basic bW9iaWxlX2Jhbmtpbmc6ZGUyNTRkM2QtY2VjMi00MzczLThiZWYtOGFjZDVmY2IyZGE4
  auth-server: Basic bWJfY2xpZW50aWQ6WTJoaGJXRnpaV055WlhRPQ==
  channel-manager: Basic Y2hhbm5lbC1zZXJ2aWNlOkMtc2c2T0dUNC8qOEN5ND0=


app:
  security:
    keystore-name: authorization.p12
    keystore-password: Cleo$patra
    key-alias: ecl-auth



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://10.20.2.148:7772/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

user:
  username: admin
  password: password

external:
  portal: https://google.com
demo:
  send: true